# Generated by Django 4.0.2 on 2022-02-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
