# Generated by Django 4.0.2 on 2022-02-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_company_email_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
